### ISSUE TITLE
ASK

### ISSUE THREAD

**Issue by deffan10** [ryanaidilp/sistem_absensi_pegawai#29]
I already get over it. About how to make admin voyager account. But, what i want to ask is. all user can open the "unduh data presentasi" ?

![image](https://user-images.githubusercontent.com/49578199/108873722-00449580-762e-11eb-8959-84da064a6b2d.png)

and 1 more, when i open localhost:8000/admin to login voyager i am back to home with qr code

**Comment by deffan10** [comment]
sorry wrong screenshot
![image](https://user-images.githubusercontent.com/49578199/108873879-2b2ee980-762e-11eb-9df9-b12c6c643162.png)

**Comment by ryanaidilp** [comment]
Yes, the "unduh data presensi" feature can be accessed by all employees because most of the employees in the office where this app are used are not really familiar in using authorization (login, etc), so to make it easier for them I give access to download attendance data for all employees. If you don't want to display this feature to all employees, you can create a gate/middleware to make access to this feature strict only to a specified user. I have initialized laravel/ui in the repository, you just need to implement the authorization feature.

**Comment by deffan10** [comment]
Ok. its a nice button to help them. 
Btw when i logging in into voyager admin using admin@mail.com admin123, always get redirected into first scree. 
![image](https://user-images.githubusercontent.com/49578199/108963454-b18a1080-76ac-11eb-9f0f-20d8df10cc18.png)

and where i can change the time for work and for home ?
and we must insert users from csv ? cant add it from gui admin ?

**Comment by deffan10** [comment]
and i already try di apk "SIAP" and try to logging in with user admin "082123456789" with admin123. cant logged in.
![image](https://user-images.githubusercontent.com/49578199/108964779-81dc0800-76ae-11eb-9436-66f4cf02eea6.png)

**Comment by ryanaidilp** [comment]
check your laravel.log files then paste it here
